### ISSUE TITLE
Wrong branch

### ISSUE THREAD

**Issue by 6r1d** [0x009922/explorer-deploy-dev-tool#1]
It seems there's a missing branch for BCE to fix. Which one should I pick?

Example:

`elixir ./assistant.exs install explorer`

Log:

```
Installing explorer
    Updating git repository `https://github.com/soramitsu/iroha2-block-explorer-backend.git`
error: failed to find branch `feat/new-web-methods`

Caused by:
  cannot locate remote-tracking branch 'origin/feat/new-web-methods'; class=Reference (4); code=NotFound (-3)
** (File.CopyError) could not copy from "./.tmp-cargo/bin/iroha2_explorer_web" to "./.explorer/iroha2_explorer_web": no such file or directory
    (elixir 1.14.0) lib/file.ex:838: File.cp!/3
    (elixir 1.14.0) lib/code.ex:1245: Code.require_file/2
```

**Comment by 0x009922** [comment]
Closed with #3
